### ISSUE TITLE
Feature: Add a Configuration Parameter to Make the Prefix of the Tracking Table Configurable

### ISSUE THREAD

**Issue by nassor** [conduitio-labs/conduit-connector-oracle#70]
## Description

Currently, the tracking table prefix in the application is hard-coded, which can cause conflicts with other tables in the database when multiple instances of the application share the same database. To address this issue, I would like to request a feature that allows users to configure the prefix of the tracking table through a configuration parameter.

**Comment by voscob** [comment]
@nassor 
Is it not the same issue?
https://github.com/conduitio-labs/conduit-connector-oracle/issues/63

**Comment by hariso** [comment]
> @nassor Is it not the same issue? #63

You're right. After talking to @nassor, there's another intention behind this, and that is that other tools that "embed" Conduit want to have custom prefixes.

**Comment by simonl2002** [comment]
Fixed in #73
